### PR TITLE
Sync 6.3.1 back to develop

### PR DESCRIPTION
**Pull request by CongMa13**

### CODE REVIEW

**Review by cgmillette — DISMISSED** [review]
LGTM - just need to address the multiple blank lines issue below

**Review by cgmillette — APPROVED** [review]
LGTM

**Review by cgmillette — APPROVED** [review]

**Comment by CongMa13** [comment]
Hi @amd-jnovotny , could you take a quick look at this PR again. 

Sorry to ask you to review the same stuff again.  The same content is just copied among branches. Have to call you every time. 😄

**Review by amd-jnovotny — APPROVED** [review]
looks good

**Pull request merged**
