### PR TITLE
updated the changelog for 6.3

### PR DESCRIPTION
**Pull request by spolifroni-amd**

### CODE REVIEW

**Review by cgmillette — APPROVED** [review]

**Comment by cgmillette** [comment]
@CongMa13 can you please create a cherry-pick for this in the 6.3 release?

**Comment by CongMa13** [comment]
Hi @spolifroni-amd  and @cgmillette , I have merged PR 281 into this PR since they both edited changelog of hiptensor. 

Could you please review this PR again?

**Comment by spolifroni-amd** [comment]
> Hi @spolifroni-amd and @cgmillette , I have merged PR 281 into this PR since they both edited changelog of hiptensor.
> 
> Could you please review this PR again?

lgtm 👍

**Review by cgmillette — APPROVED** [review]
LGTM

**Comment by cgmillette** [comment]
@samjwu Can you please have a look at the docs failure?

**Comment by CongMa13** [comment]
Updated some dead links in README.md which caused doc building failure. 

@ROCm/rocm-documentation Could anyone approve this PR?

**Comment by CongMa13** [comment]
The target branch is [ROCm:release/rocm-rel-6.3](https://github.com/ROCm/hipTensor/tree/release/rocm-rel-6.3) now.  This PR can be closed now. 

The new PR is https://github.com/ROCm/hipTensor/pull/289

**Pull request closed without merging**
