### PR TITLE
Merge develop to release staging 6.4

### PR DESCRIPTION
**Pull request by CongMa13**
Made this commit the child of develop and release-staging-6.4. 
So they can both fast-forward to this commit.

image

### CODE REVIEW

**Review by cgmillette — APPROVED** [review]
lgtm

**Comment by CongMa13** [comment]
@ROCm/rocm-documentation Branch `release-staging/rocm-rel-6.4` will be overwritten by develop branch in this PR. The docs in develop branch have been approved before.

**Comment by CongMa13** [comment]
Hi @amd-jnovotny, could you help to review this PR? Branch release-staging/rocm-rel-6.4 will be overwritten by develop branch in this PR. The docs in develop branch have been approved before.  😄

**Review by amd-jnovotny — APPROVED** [review]
Looks good

**Comment by amd-jnovotny** [comment]
@CongMa13 Done! I thought this looked familiar. :)

**Pull request merged**
