### PR TITLE
Doc folder organization

### PR DESCRIPTION
**Pull request by SwRaw**
Organizing the doc files into respective subfolders

### CODE REVIEW

**Review by lpaoletti — COMMENTED** [review]
There's not much on the landing page. 
Let's get rid of the What is page and place those paragraphs on the landing page:

image

**Comment by SwRaw** [comment]
@lpaoletti Done. Please approve.

**Review by lpaoletti — APPROVED** [review]

**Comment by SwRaw** [comment]
@cgmillette Could you please merge this PR. It contains minor changes related to documentation conventions.

**Review by cgmillette — APPROVED** [review]
LGTM

**Pull request merged**
